### ISSUE TITLE
why you doing this?

### ISSUE THREAD

**Issue by kevlarballoons** [Disconnect24/disconnect24.xyz#2]
if you want to help I'm sure larsen will let you guys

**Comment by TheMrIron2** [comment]
A multitude of reasons. Spotlight was previously a developer for RiiConnect24 but left because of development team issues (management and priorities).

The goal of Disconnect24 is simple; we want WC24 to be revived to the fullest. This means no cop-out, poor code - RC24 has some notoriously dodgy code across almost all of its service - but fast and efficient systems. Another issue with RC24 is that things have to be done manually by the developers - with DC24, we want to make everything dynamic and powered by the Google Cloud Engine service. We are also beginning work on reverse-engineering Nintendo Channel encryption (see wc24-decrypt).

So why have we made this project? It's simple; by providing competition, we force RC24 to up their game to match these standards. We are not trying to take down RiiConnect24; we are trying to improve the project by showing RC24 this stable, efficient code and hoping they can learn from this and improve their code.

**Comment by kevlarballoons** [comment]
ah mk
